version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: deepsearch-mockgen-cli
    main: ./
    binary: deepsearch-mockgen-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

release:
  mode: append
  github:
    owner: FournyP
    name: deepsearch-mockgen-cli

changelog:
  disable: true
