// Code generated by MockGen. DO NOT EDIT.
// Source: src/mockgen/services/interfaces/interface_selector_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/mockgen/services/interfaces/interface_selector_interface.go -destination=tests/mockgen_mocks/services_mocks/interfaces_mocks/interface_selector_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInterfaceSelectorInterface is a mock of InterfaceSelectorInterface interface.
type MockInterfaceSelectorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceSelectorInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceSelectorInterfaceMockRecorder is the mock recorder for MockInterfaceSelectorInterface.
type MockInterfaceSelectorInterfaceMockRecorder struct {
	mock *MockInterfaceSelectorInterface
}

// NewMockInterfaceSelectorInterface creates a new mock instance.
func NewMockInterfaceSelectorInterface(ctrl *gomock.Controller) *MockInterfaceSelectorInterface {
	mock := &MockInterfaceSelectorInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceSelectorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterfaceSelectorInterface) EXPECT() *MockInterfaceSelectorInterfaceMockRecorder {
	return m.recorder
}

// Select mocks base method.
func (m *MockInterfaceSelectorInterface) Select(interfaces map[string]string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", interfaces)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockInterfaceSelectorInterfaceMockRecorder) Select(interfaces any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockInterfaceSelectorInterface)(nil).Select), interfaces)
}
