// Code generated by MockGen. DO NOT EDIT.
// Source: src/mockgen/services/interfaces/interface_finder_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/mockgen/services/interfaces/interface_finder_interface.go -destination=tests/mockgen_mocks/services_mocks/interfaces_mocks/interface_finder_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInterfaceFinderInterface is a mock of InterfaceFinderInterface interface.
type MockInterfaceFinderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceFinderInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceFinderInterfaceMockRecorder is the mock recorder for MockInterfaceFinderInterface.
type MockInterfaceFinderInterfaceMockRecorder struct {
	mock *MockInterfaceFinderInterface
}

// NewMockInterfaceFinderInterface creates a new mock instance.
func NewMockInterfaceFinderInterface(ctrl *gomock.Controller) *MockInterfaceFinderInterface {
	mock := &MockInterfaceFinderInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceFinderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterfaceFinderInterface) EXPECT() *MockInterfaceFinderInterfaceMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockInterfaceFinderInterface) Find(root string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", root)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockInterfaceFinderInterfaceMockRecorder) Find(root any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockInterfaceFinderInterface)(nil).Find), root)
}
