// Code generated by MockGen. DO NOT EDIT.
// Source: src/mockgen/services/interfaces/mock_path_builder_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/mockgen/services/interfaces/mock_path_builder_interface.go -destination=tests/mockgen_mocks/services_mocks/interfaces_mocks/mock_path_builder_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMockPathBuilderInterface is a mock of MockPathBuilderInterface interface.
type MockMockPathBuilderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMockPathBuilderInterfaceMockRecorder
	isgomock struct{}
}

// MockMockPathBuilderInterfaceMockRecorder is the mock recorder for MockMockPathBuilderInterface.
type MockMockPathBuilderInterfaceMockRecorder struct {
	mock *MockMockPathBuilderInterface
}

// NewMockMockPathBuilderInterface creates a new mock instance.
func NewMockMockPathBuilderInterface(ctrl *gomock.Controller) *MockMockPathBuilderInterface {
	mock := &MockMockPathBuilderInterface{ctrl: ctrl}
	mock.recorder = &MockMockPathBuilderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMockPathBuilderInterface) EXPECT() *MockMockPathBuilderInterfaceMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockMockPathBuilderInterface) Build(searchDir, outputDir, interfacePath, interfaceName string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", searchDir, outputDir, interfacePath, interfaceName)
	ret0, _ := ret[0].(string)
	return ret0
}

// Build indicates an expected call of Build.
func (mr *MockMockPathBuilderInterfaceMockRecorder) Build(searchDir, outputDir, interfacePath, interfaceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockMockPathBuilderInterface)(nil).Build), searchDir, outputDir, interfacePath, interfaceName)
}
