// Code generated by MockGen. DO NOT EDIT.
// Source: src/mockgen/services/interfaces/mock_batch_generator_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/mockgen/services/interfaces/mock_batch_generator_interface.go -destination=tests/mockgen_mocks/services_mocks/interfaces_mocks/mock_batch_generator_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	reflect "reflect"

	models "github.com/FournyP/deepsearch-mockgen-cli/src/mockgen/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMockBatchGeneratorInterface is a mock of MockBatchGeneratorInterface interface.
type MockMockBatchGeneratorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMockBatchGeneratorInterfaceMockRecorder
	isgomock struct{}
}

// MockMockBatchGeneratorInterfaceMockRecorder is the mock recorder for MockMockBatchGeneratorInterface.
type MockMockBatchGeneratorInterfaceMockRecorder struct {
	mock *MockMockBatchGeneratorInterface
}

// NewMockMockBatchGeneratorInterface creates a new mock instance.
func NewMockMockBatchGeneratorInterface(ctrl *gomock.Controller) *MockMockBatchGeneratorInterface {
	mock := &MockMockBatchGeneratorInterface{ctrl: ctrl}
	mock.recorder = &MockMockBatchGeneratorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMockBatchGeneratorInterface) EXPECT() *MockMockBatchGeneratorInterfaceMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockMockBatchGeneratorInterface) Generate(targets []models.MockTarget, updates chan<- models.ProgressUpdate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Generate", targets, updates)
}

// Generate indicates an expected call of Generate.
func (mr *MockMockBatchGeneratorInterfaceMockRecorder) Generate(targets, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockMockBatchGeneratorInterface)(nil).Generate), targets, updates)
}
