// Code generated by MockGen. DO NOT EDIT.
// Source: src/mockgen/services/interfaces/mock_generator_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/mockgen/services/interfaces/mock_generator_interface.go -destination=tests/mockgen_mocks/services_mocks/interfaces_mocks/mock_generator_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	reflect "reflect"

	models "github.com/FournyP/deepsearch-mockgen-cli/src/mockgen/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMockGeneratorInterface is a mock of MockGeneratorInterface interface.
type MockMockGeneratorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMockGeneratorInterfaceMockRecorder
	isgomock struct{}
}

// MockMockGeneratorInterfaceMockRecorder is the mock recorder for MockMockGeneratorInterface.
type MockMockGeneratorInterfaceMockRecorder struct {
	mock *MockMockGeneratorInterface
}

// NewMockMockGeneratorInterface creates a new mock instance.
func NewMockMockGeneratorInterface(ctrl *gomock.Controller) *MockMockGeneratorInterface {
	mock := &MockMockGeneratorInterface{ctrl: ctrl}
	mock.recorder = &MockMockGeneratorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMockGeneratorInterface) EXPECT() *MockMockGeneratorInterfaceMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockMockGeneratorInterface) Generate(target models.MockTarget) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", target)
	ret0, _ := ret[0].(error)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockMockGeneratorInterfaceMockRecorder) Generate(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockMockGeneratorInterface)(nil).Generate), target)
}
