// Code generated by MockGen. DO NOT EDIT.
// Source: src/mockgen/services/interfaces/mockgen_reporter_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/mockgen/services/interfaces/mockgen_reporter_interface.go -destination=tests/mockgen_mocks/services_mocks/interfaces_mocks/mockgen_reporter_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMockgenReporterInterface is a mock of MockgenReporterInterface interface.
type MockMockgenReporterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMockgenReporterInterfaceMockRecorder
	isgomock struct{}
}

// MockMockgenReporterInterfaceMockRecorder is the mock recorder for MockMockgenReporterInterface.
type MockMockgenReporterInterfaceMockRecorder struct {
	mock *MockMockgenReporterInterface
}

// NewMockMockgenReporterInterface creates a new mock instance.
func NewMockMockgenReporterInterface(ctrl *gomock.Controller) *MockMockgenReporterInterface {
	mock := &MockMockgenReporterInterface{ctrl: ctrl}
	mock.recorder = &MockMockgenReporterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMockgenReporterInterface) EXPECT() *MockMockgenReporterInterfaceMockRecorder {
	return m.recorder
}

// NoInterfacesFound mocks base method.
func (m *MockMockgenReporterInterface) NoInterfacesFound() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NoInterfacesFound")
}

// NoInterfacesFound indicates an expected call of NoInterfacesFound.
func (mr *MockMockgenReporterInterfaceMockRecorder) NoInterfacesFound() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoInterfacesFound", reflect.TypeOf((*MockMockgenReporterInterface)(nil).NoInterfacesFound))
}

// ProgressFailed mocks base method.
func (m *MockMockgenReporterInterface) ProgressFailed(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProgressFailed", err)
}

// ProgressFailed indicates an expected call of ProgressFailed.
func (mr *MockMockgenReporterInterfaceMockRecorder) ProgressFailed(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProgressFailed", reflect.TypeOf((*MockMockgenReporterInterface)(nil).ProgressFailed), err)
}
