// Code generated by MockGen. DO NOT EDIT.
// Source: src/mockgen/services/interfaces/progress_reporter_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/mockgen/services/interfaces/progress_reporter_interface.go -destination=tests/mockgen_mocks/services_mocks/interfaces_mocks/progress_reporter_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	reflect "reflect"

	models "github.com/FournyP/deepsearch-mockgen-cli/src/mockgen/models"
	gomock "go.uber.org/mock/gomock"
)

// MockProgressReporterInterface is a mock of ProgressReporterInterface interface.
type MockProgressReporterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProgressReporterInterfaceMockRecorder
	isgomock struct{}
}

// MockProgressReporterInterfaceMockRecorder is the mock recorder for MockProgressReporterInterface.
type MockProgressReporterInterfaceMockRecorder struct {
	mock *MockProgressReporterInterface
}

// NewMockProgressReporterInterface creates a new mock instance.
func NewMockProgressReporterInterface(ctrl *gomock.Controller) *MockProgressReporterInterface {
	mock := &MockProgressReporterInterface{ctrl: ctrl}
	mock.recorder = &MockProgressReporterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgressReporterInterface) EXPECT() *MockProgressReporterInterfaceMockRecorder {
	return m.recorder
}

// Report mocks base method.
func (m *MockProgressReporterInterface) Report(total int, updates <-chan models.ProgressUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Report", total, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Report indicates an expected call of Report.
func (mr *MockProgressReporterInterfaceMockRecorder) Report(total, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockProgressReporterInterface)(nil).Report), total, updates)
}
