// Code generated by MockGen. DO NOT EDIT.
// Source: src/mockgen/services/interfaces/prompter_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/mockgen/services/interfaces/prompter_interface.go -destination=tests/mockgen_mocks/services_mocks/interfaces_mocks/prompter_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPrompterInterface is a mock of PrompterInterface interface.
type MockPrompterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPrompterInterfaceMockRecorder
	isgomock struct{}
}

// MockPrompterInterfaceMockRecorder is the mock recorder for MockPrompterInterface.
type MockPrompterInterfaceMockRecorder struct {
	mock *MockPrompterInterface
}

// NewMockPrompterInterface creates a new mock instance.
func NewMockPrompterInterface(ctrl *gomock.Controller) *MockPrompterInterface {
	mock := &MockPrompterInterface{ctrl: ctrl}
	mock.recorder = &MockPrompterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrompterInterface) EXPECT() *MockPrompterInterfaceMockRecorder {
	return m.recorder
}

// Prompt mocks base method.
func (m *MockPrompterInterface) Prompt(question, defaultValue string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prompt", question, defaultValue)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prompt indicates an expected call of Prompt.
func (mr *MockPrompterInterfaceMockRecorder) Prompt(question, defaultValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prompt", reflect.TypeOf((*MockPrompterInterface)(nil).Prompt), question, defaultValue)
}
